daemonize: false

nfacctd_port: 2055
nfacctd_time_new: true

plugins: pgsql[flows]

aggregate[flows]: src_host, dst_host, src_port, dst_port, proto

sql_host[flows]: 127.0.0.1
sql_port[flows]: 55432
sql_db[flows]: pmacct
sql_table[flows]: acct
sql_table_version[flows]: 1
sql_user[flows]: pmacct
sql_passwd[flows]: pmacctpass

sql_refresh_time[flows]: 60
sql_history[flows]: 1m
sql_history_roundoff[flows]: mh
